### PR TITLE
Prefix component with product on FXP and SP3 projects

### PR DESCRIPTION
**Pull request by davehunt**
Both projects have the components field on the create/update screens. This sync is already working, but I'd like to include the product as we have some generic/shared components.

### CODE REVIEW

**Review by leplatrem — APPROVED** [review]
LGTM

With this config, if both `Core::General` and `General` components exist, they will be both assigned (`use_bug_component` is true by default)

**Comment by davehunt** [comment]
> With this config, if both `Core::General` and `General` components exist, they will be both assigned (`use_bug_component` is true by default)

Ah, I was a little confused by the ability to set multiple components. So how do I make it so only `Core::General` would be set? Would it be as follows?

```
jira_components:
  use_bug_component: false
  use_bug_component_with_product_prefix: true
```

**Comment by davehunt** [comment]
@leplatrem please could you take another look?

**Review by leplatrem — APPROVED** [review]
Great 💯 

(It may be a sign that this setting does not have the right default value)

**Review by Micha3L2020 — APPROVED** [review]

**Pull request merged**
