### PR TITLE
[sp3][config] Add configuration for the Speedometer 3 project

### PR DESCRIPTION
**Pull request by davehunt**

### CODE REVIEW

**Review by bsieber-mozilla — APPROVED** [review]
LGTM!

**Comment by leplatrem** [comment]
Can we link the Jira admin tickets here in order to follow the permissions changes for the `SP3` project?

**Comment by davehunt** [comment]
> Can we link the Jira admin tickets here in order to follow the permissions changes for the `SP3` project?

@leplatrem is this something I need to do? I added the Jira Automation user to the Bots role myself. What else is needed?

**Comment by bsieber-mozilla** [comment]
Made [this support request](https://mozilla-hub.atlassian.net/servicedesk/customer/portal/4/SDD-12313?created=true) for nonprod env; @davehunt provided the bot permissions through admin-project priviledges (no support request was required; thank you)

**Comment by davehunt** [comment]
@bsieber-mozilla can you confirm if this is live?

**Comment by bsieber-mozilla** [comment]
@davehunt, apologies for the delay in getting this tag live (we've begun to change the nonprod testing approach with this recent release)

this tag is part of the newest release 4.1.4; [this is live as of today 2/14](https://mozilla.slack.com/archives/C016BTJKM9B/p1676416738124009).

**Comment by davehunt** [comment]
@bsieber-mozilla thanks, it's working nicely!

**Pull request merged**
