### PR TITLE
Update to remote-link title; use URL, set icon favicon url.

### PR DESCRIPTION
**Pull request by bsieber-mozilla**
#202 

After testing locally, this doesn't add the favicon--but is one step closer to what was previously expected.

The atlassian-python-api does not accept "icon" as part of the api, however if we use the Jira REST API, we should be able to add a link to a favicon.

### CODE REVIEW

**Comment by bsieber-mozilla** [comment]
@grahamalama do you think we should move forward with something like this? 

_(If so, we can look into modifying the atlassian-python-api to add the `icon` parameter internal to the remote-issue api call, or moving away from the atlassian-python-api to use the rest api and add the icon later.)_

**Comment by grahamalama** [comment]
Yeah, since the client library doesn't support adding favicons and we're already adding some more context requested in #202 (i.e. `Bugzilla Bug 1234567`), maybe it's best to close this PR and instead:
- "Eject" from `atlassian-python-api` in favor of our own, internal library
or 
- Submit a PR to `atlassian-python-api` to supporting remote link favicons

**Comment by bsieber-mozilla** [comment]
@grahamalama thanks for the addition; I've pointed to the new commit hash to pick those changes up.

**Review by grahamalama — APPROVED** [review]
Do you want to set `icon_title` as well?

Also, could you create an issue to revert back to PyPI-released version of `atlassian-python-api` once that patch makes it into the next release?

**Comment by bsieber-mozilla** [comment]
> Do you want to set `icon_title` as well?
When looking at the API and testing this adds a tooltip, but isn't essential (just like `[icon_title](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-remote-links/#api-rest-api-3-issue-issueidorkey-remotelink-post)`). 

I can add it in though.


> Also, could you create an issue to `revert back` to PyPI-released version of `atlassian-python-api` once that patch makes it into the next release?

Currently the toml is pointed to the previous commit when our team last updated the `atlassian-python-api.` 

Good callout; I did not see an issue already made, so I've made a new one for us to migrate to the official release when the new additions are applied.

https://github.com/mozilla/jira-bugzilla-integration/issues/221

**Pull request merged**
