### PR TITLE
Non-fixed bug closing should also close jira items

### PR DESCRIPTION
**Pull request by gijsk**
Noticed that WONTFIX bugs don't get automatically closed on JIRA. I think this should fix that?

### CODE REVIEW

**Comment by gijsk** [comment]
Might be nice to also update the "resolution field" on JIRA? But I don't know how to do that.

**Review by leplatrem — APPROVED** [review]
> Might be nice to also update the "resolution field" on JIRA? But I don't know how to do that.

Apparently, the `.set_issue_status()` method also accepts `fields`. But it would probably deserve a dedicated issue/PR.

**Comment by gijsk** [comment]
> > Might be nice to also update the "resolution field" on JIRA? But I don't know how to do that.
> 
> Apparently, the `.set_issue_status()` method also accepts `fields`. But it would probably deserve a dedicated issue/PR.

I'm guessing that means more changes than just the yaml file? Or do I "just" need a separate mapping of sorts? Sorry, I'm still very not-familiar with this repository! 😅

**Comment by leplatrem** [comment]
> Separate PR sounds good. I'm guessing that means more changes than just the yaml file? 

Unfortunately, you guess right :) You would need to modify the action code (`jbi/actions/default_with_assignee_and_status.py`), add some unit tests, and test it on STAGE. You can open an issue for now, and if you feel like doing all this, assign it to you ;)

**Comment by gijsk** [comment]
OK, I filed #200 . Can we land this in the meantime? :-)

**Comment by grahamalama** [comment]
@gijsk yep! Merging now.

**Comment by grahamalama** [comment]
@gijsk let us know when you have to verify these changes in staging, then we can slate it for an upcoming release

**Comment by gijsk** [comment]
@grahamalama I'm sorry but I don't know any of the staging details (location of bmo/jira instances, credentials, etc.) so I don't know how to do that...

**Pull request merged**
